const JUMP_HEIGHT = 10;

const GRAVITY = 0.4;

const SPEED = 8;

const FRAME_RATE = 60;

// Default values
const MAX_WIDTH = 640;
const DEFAULT_WIDTH = 320;
const DEFAULT_HEIGHT = 512;
const DEFAULT_DOODLER_WIDTH = 46;
const DEFAULT_DOODLER_HEIGHT = 45;
const DEFAULT_PLATFORM_WIDTH = 57;
const DEFAULT_PLATFORM_HEIGHT = 15;
const PLATFORM_SPEED = 2;
const DEFAULT_MOVING_PLATFORM_CHANCE = 0.15;
const MIN_PLATFORM_DIFFERENCE = 30;
const MAX_PLATFORM_DIFFERENCE = 90;
const DEFAULT_SPRING_WIDTH = 18;
const DEFAULT_SPRING_HEIGHT = 12;
const DEFAULT_SPRING_HEIGHT_EXTENDED = 28;
const SPRING_PLATFORM_CHANCE = 0.2;
